---
title: "Bernhardt and O'Connor 2021 Paper Summary"
author: "Meredith Miller, Caitlin Bergman, Mike Chung, Lucy Wall"
date: "10/19/2021"
output:
    pdf_document
---

\newpage

# Prediscussion 

*Aquatic biodiversity enhances multiple nutrition benefits to humans*

**Authors: Joey R. Bernhardt, and Mary I. O ’Connor. **

Group Members: Caitlin Bergman, Mike Chung, Lucy Wall, Meredith Miller 

## Key Terms 
- Ecological Functional Diversity 
- Recommended Dietary Allowance (RDA) 
- Food security 
- Micronutrients 
- Macronutrients 
- Pelagic and demersal 
- Nutrient targets (NT) 
- Complementarity 


## General Questions 

1. There are three main hypotheses tested in this paper. What are they, and what results would support each hypothesis? (*Hint - the first two hypotheses relate to nutritional benefits, and the third hypothesis relates to nutritional risks) 
2. What metrics were used to determine relative nutritional content of edible tissues? 3. How was the data in this paper collected/produced? What are some of the benefits and disadvantages of this? 
3. What gender and age group of RDA was used for this study? Why did they look at this group? Do the results still relate to impacts on the “RDA targets” for individuals outside of this group? 
4. Why is it important that this study included both macronutrients and micronutrients? Why did they select the nutrients they did?

## Key Findings 
1. Figure 2 
a. How does this figure contribute to the conclusions of the paper? 
b. How do the findings differ between macronutrients and micronutrients? c. What is the purpose of the bottom graph? 
d. Think about where this data comes from. How does this affect the applications of the results? 
2. Figure 3 
a. How do the results in this figure contribute to the conclusions of the paper? b. How do the results for protein differ from the results for micronutrients? c. What methods were used to produce these figures? How does this compare to place-based diets? 
3. Figure 4 
a. Which hypothesis does this figure relate to? How does it help answer this question? 
b. What is the x-axis measuring in Figure 4A? What does this mean in the context of the human consumption of seafood? 
c. What does this figure make you think about the risks vs rewards of increased species richness associated with human diets? 
4. Applications and Future Research 
a. Read this quote: “Finding a balance between seafood biodiversity, seafood biomass consumption, and the resulting risks and benefits will be critical for both human and ecosystem health.” (p. 7) 
b. What implications do these findings have for a food security standpoint? c. What do the findings mean from a sustainability standpoint? 
d. Armed with this information, how might this be applied at a local scale, and how might it be applied at a global scale? 
e. What are the limitations of these findings, or obstacles to applying these results?


# **Broad Questions**

## **Question 1: Is this paper still useful with an error in Figure 5?**
For this specific paper, the error doesn’t negate the significance of their main findings related to the effect of species richness on nutritional benefits. The rest of the paper is still valid and has interesting and useful conclusions. However, this does not hold true for all errors that occur in published papers. It is important to think critically when reading papers, and not to assume that something is true just because it was written in one paper.

## **Question 2: How would this error affect you if you were basing your research off of this paper? How does this make you think about the use of published papers as a whole?** 
The error in Figure 5 was an isolated issue in this text. Cole mentioned how he would not have caught it if the code wasn’t openly available online. As scientists, we base a lot of our methods and assumptions off published papers, relying on assumptions of their factuality. It is difficult to fully understand all of the statistical analysis of this paper, but researchers shouldn’t necessarily go into it assuming that the peer-review process eliminated all mistakes or misunderstandings. This paper is a good reminder to not take every piece of primary literature like a static, factual conclusion. It made us think about the rigidity of the publishing process and the hurdles scientists must overcome (or try to overcome) to make corrections or edits in their work. We also considered how these roadblocks may limit us as we currently can’t treat our papers as living, working documents that can be updated and improved through time.

## **Changing Viewpoints**
Initially most students went into this paper trusting that the statistical analysis of the data was performed correctly, but as Cole mentioned how Figure 5 was improperly interpreted students began to look more critically. Many students were discussing the pros and cons of the author’s data collection methods, but nobody thought (or had the modelling background specialty) to second guess the accuracy of the interpretation. As discussed in Question 2, after discussing the paper we gained a deeper understanding of critical thinking approaches to interpreting studies, as well as the benefits of open-source, transparent methods, and open dialogue in writing and publishing scientific articles.

## **Connections**
These discussion questions relate to the methodology of the paper. The transparency of the methodology made it possible for the mistake in Figure 5 to be identified. The analyses used to create the figure were described in the supplementary methods, and the code was available online, which allowed Cole to understand exactly how the figure was created. This demonstrates the benefits of open-source science, since without transparent methods, it is much harder or impossible for mistakes to be noticed by the general scientific community. 

## **Epistemology** 
The following discussion had us question our current understanding of taking scientific findings at face value. Although there were errors in some of the analyses, this did not negate all the significance of their findings. It did however highlight the requirements for critical thinking and the importance of fully understanding the data and approach to analyses. Science should therefore be a collaborative effort, as someone who is an expert in one field may not have a deep understanding of other specialties. 

## **How Science Happens**
This paper made us think about how research is used once published, and the problems that might occur as a result. Once a paper has been peer reviewed and published, it is often regarded as fact and no longer subject to refutation. If an error makes it through the peer review process, other studies may reference it without investigating the exact methodology that was used. If an error is found, it can be a long, difficult, and expensive process to change it. Even once a paper is changed, the change may not be seen by everyone who reads the paper, depending on where people are accessing it. These issues make it easy for a small mistake to spread once it has been published, since other scientists may cite the original paper without noticing (or having the tools to notice) the mistake.


